In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
a[0], a[1]

a[0:3]

array([1, 2, 3])

datatype = .dtype
to get the sum of a row or column in an array, we use axis, where axis(0) = column, axis(1) = row

In [6]:
a.dtype

dtype('int32')

In [7]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
print(A[1][0])

print(A[0:2])


A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])


4
[[1 2 3]
 [4 5 6]]
[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [9]:
print(A.sum(axis=0))

print()

print(A.sum(axis=1))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [ ]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.array([20, 21, 22, 23, 24])
a

array([20, 21, 22, 23, 24])

In [ ]:
a += 100
a

array([720, 721, 722, 723, 724])

In [ ]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
print(a[0], a[-1])

0 3


In [ ]:
print(a[[True, False, False, True]])

[0 3]


In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >=2

array([False, False,  True,  True])

In [ ]:
l = list(range(1000))

In [11]:
a = np.arange(1000)

In [18]:
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [19]:
%time sum([x **2 for x in l ])

CPU times: total: 0 ns
Wall time: 1.01 ms


332833500