In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [8]:
a[0], a[1]

a[0:3]

array([1, 2, 3])

datatype = .dtype
to get the sum of a row or column in an array, we use axis, where axis(0) = column, axis(1) = row

In [10]:
a.dtype

dtype('int32')

In [12]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [20]:
print(A[1][0])

print(A[0:2])


A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])


4
[[1 2 3]
 [4 5 6]]
[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [19]:
print(A.sum(axis=0))

print()

print(A.sum(axis=1))

[12 15 18]

[ 6 15 24]


In [21]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [23]:
a = np.array([20, 21, 22, 23, 24])
a

array([20, 21, 22, 23, 24])

In [30]:
a += 100
a

array([720, 721, 722, 723, 724])

In [31]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [35]:
print(a[0], a[-1])

0 3


In [38]:
print(a[[True, False, False, True]])

[0 3]
